### ISSUE TITLE
Issue about the loss computing based on mining hard negatives

### ISSUE THREAD

**Issue by zhufeijuanjuan** [technicolor-research/dsve-loc#18]
thank you for your work in advance.
according to the paper, "for each positvie pair in the batch, the negative sample is selected in this batch as the one that has the highest similarity with the query image/sentence while not being associate with it." . 
issue 1:  as we know, there are five sentences labeled to captioning a image, so how to avoid the selected negative sentence comes from the caption list in the same image.
issue 2: in  some cases,  different images may have the same caption sentence, how to avoid the selected negative image has the same caption sentence as the positive sampler.
Thx.

**Comment by M-Eng** [comment]
Hi,

Indeed both of those issue are important and are related to the hardness of the negative element selected.
When selecting negative examples, we run the risk of selecting false negative which would be extremely harmful to training stability.

Here are a few points we experimented with and that might be helpful to you:

- We tried making batches by hand to make sure that two captions from the same image did not end up in the same batch. It didn't yield significant improvement so we discarded it for simplicity.

- We tried selecting the hardest negative at the dataset level instead of the of the batch level we observe issue 2 and we were not able to train models with this approach.

- In the end, the hardness of the negative is controlled by the batch size, the bigger, the batch, the harder the negative, it might not be an ideal solution but it was sufficient. 

- We've observed that increasing the batch size improved the performance and we expect to reach a plateau followed by a decrease in performance by further increasing the batch size (and starting to select false negative) but we were not able to run those test due to memory limitations at the time.

Finally, and to answer your question directly: for issue number one we assume that our batch where small enough and the random shuffling was enough to make it very unlikely to have two captions coming from the same image in the same batch.

For your second point, we didn’t implement specific strategy and relied on the batch size to control the hardness of the negative element. 

Best,
Martin

**Comment by zhufeijuanjuan** [comment]
> Hi,
> 
> Indeed both of those issue are important and are related to the hardness of the negative element selected.
> When selecting negative examples, we run the risk of selecting false negative which would be extremely harmful to training stability.
> 
> Here are a few points we experimented with and that might be helpful to you:
> 
> * We tried making batches by hand to make sure that two captions from the same image did not end up in the same batch. It didn't yield significant improvement so we discarded it for simplicity.
> * We tried selecting the hardest negative at the dataset level instead of the of the batch level we observe issue 2 and we were not able to train models with this approach.
> * In the end, the hardness of the negative is controlled by the batch size, the bigger, the batch, the harder the negative, it might not be an ideal solution but it was sufficient.
> * We've observed that increasing the batch size improved the performance and we expect to reach a plateau followed by a decrease in performance by further increasing the batch size (and starting to select false negative) but we were not able to run those test due to memory limitations at the time.
> 
> Finally, and to answer your question directly: for issue number one we assume that our batch where small enough and the random shuffling was enough to make it very unlikely to have two captions coming from the same image in the same batch.
> 
> For your second point, we didn’t implement specific strategy and relied on the batch size to control the hardness of the negative element.
> 
> Best,
> Martin

**Comment by zhufeijuanjuan** [comment]
Thanks for your replay. The impact of the two issues depends on dataset used. In my dataset, one special utterance is used to caption many different images. So some strategies should be used. I will try it. Thx again.

Best Regard,
Fei
