### ISSUE TITLE
Using a different word2vec for sentence encoding

### ISSUE THREAD

**Issue by sachinpuranik99** [technicolor-research/dsve-loc#3]
Do you see suspect issues if someone removes the skip-thought word2vec embeddings and uses a different word2vec trained on a different corpus and keeps all the other parameters intact?

I tried this experiment and the results were not pleasant.

**Comment by M-Eng** [comment]
By keeping all the other parameters intact, are you talking about the model weights (resnet, sru, ..)?

If yes then it makes sense you obtain unpleasant results, the model was trained using the skip-thought word embedding and expect the words to use that representation. 

However if you replace the word embedding with word2vec and then retrain the whole model, you should obtain similar results to the one reported in the paper. 

I did some experiment with word embedding, I tried using fastText. I was able to obtain a decent model with slightly lower performance (a few percent) than the one available here.

**Comment by sachinpuranik99** [comment]
> If yes then it makes sense you obtain unpleasant results, the model was trained using the skip-thought word embedding and expect the words to use that representation.

I finetuned the whole model with the rest of the architecture intact. Only the word2vec was changed. 

> I did some experiment with word embedding, I tried using fastText. I was able to obtain a decent model with slightly lower performance (a few percent) than the one available here.

Could you please post the link for the fastText model again? I don't see the link here. Thanks.

**Comment by M-Eng** [comment]
Sorry, I don't have the fastText model anymore. 
But I checked my logs and found a couple of results reaching ~65 R@1  in caption retrieval with the fastText word embedding (keeping all the other parameters the same but training from scratch). I used the fastText model available online trained on the wiki corpus.

I would suggest retraining from scratch instead of fine-tuning. The weights learned by the SRU are deeply related to the skip-thought word representation. Fine-tuning from that position seems likely to fail.

If you don't want to retrain everything you could try keeping the image pipeline frozen, and training only the SRU from scratch.

**Comment by sachinpuranik99** [comment]
Thanks a lot for your response.
